const actions = {
    ACCOUNT_LOG: 'AUTH_LOG',
    ACCOUNT_LOG_IN: 'AUTH_LOG_IN',
    ACCOUNT_LOG_OUT: 'AUTH_LOG_OUT',
    ACCOUNT_LOG_ERROR: 'ACCOUNT_LOG_ERROR',
    ACCOUNT_UPDATE_USENAME: 'ACCOUNT_UPDATE_USENAME',
    ACCOUNT_UPDATE_PASSWORD: 'ACCOUNT_UPDATE_PASSWORD',
    ACCOUNT_UPDATE_EMAIL: 'ACCOUNT_UPDATE_EMAIL'
}

export {
    actions
}