const actions = {
    ACCOUNT_LOG: 'AUTH_LOG',
    ACCOUNT_LOG_IN: 'AUTH_LOG_IN',
    ACCOUNT_LOG_OUT: 'AUTH_LOG_OUT',
    ACCOUNT_LOG_ERROR: 'ACCOUNT_LOG_ERROR',
    ACCOUNT_UPDATE_USERNAME: 'ACCOUNT_UPDATE_USERNAME',
    ACCOUNT_UPDATE_PASSWORD: 'ACCOUNT_UPDATE_PASSWORD',
    ACCOUNT_UPDATE_EMAIL: 'ACCOUNT_UPDATE_EMAIL',
    ACCOUNT_UPDATE_ERROR: 'ACCOUNT_UPDATE_ERROR',

    SCHEDULE_ADD: 'SCHEDULE_ADD',
    SCHEDULE_GET_ALL: 'SCHEDULE_GET_ALL',
    SCHEDULE_GET_ACTIVITIES: 'SCHEDULE_GET_ACTIVITIES',
    SCHEDULE_GET_ACTIONS: 'SCHEDULE_GET_ACTIONS',
    SCHEDULE_GET_TYPES: 'SCHEDULE_GET_TYPES'
}

export {
    actions
}