const actions = {
    ACCOUNT_LOG: 'AUTH_LOG',
    ACCOUNT_LOG_IN: 'AUTH_LOG_IN',
    ACCOUNT_LOG_OUT: 'AUTH_LOG_OUT',
    ACCOUNT_LOG_ERROR: 'ACCOUNT_LOG_ERROR',

    ACCOUNT_UPDATE_USERNAME: 'ACCOUNT_UPDATE_USERNAME',
    ACCOUNT_UPDATE_PASSWORD: 'ACCOUNT_UPDATE_PASSWORD',
    ACCOUNT_UPDATE_EMAIL: 'ACCOUNT_UPDATE_EMAIL',
    ACCOUNT_UPDATE_ERROR: 'ACCOUNT_UPDATE_ERROR',

    SCHEDULE_ADD: 'SCHEDULE_ADD',
    SCHEDULE_ADD_ERROR: 'SCHEDULE_ADD_ERROR',

    SCHEDULE_DELETE: 'SCHEDULE_DELETE',
    SCHEDULE_DELETE_ERROR: 'SCHEDULE_DELETE_ERROR',

    SCHEDULE_GET_ALL: 'SCHEDULE_GET_ALL',
    SCHEDULE_GET_ALL_LOADING: 'SCHEDULE_GET_ALL_LOADING',
    SCHEDULE_GET_ALL_ERROR: 'SCHEDULE_GET_ALL_ERROR',

    SCHEDULE_GET_ACTIVITIES: 'SCHEDULE_GET_ACTIVITIES',
    SCHEDULE_GET_ACTIONS: 'SCHEDULE_GET_ACTIONS',
    SCHEDULE_GET_TYPES: 'SCHEDULE_GET_TYPES',

    SETTING_ADD_ALL: 'SETTING_ADD_ALL',
    SETTING_ADD_LOADING: 'SETTING_ADD_LOADING',
    SETTING_ADD_ERROR: 'SETTING_ADD_ERROR',
    
    SETTING_GET_ALL: 'SETTING_GET_ALL',
    SETTING_GET_LOADING: 'SETTING_GET_LOADING',
    SETTING_GET_ERROR: 'SETTING_GET_ERROR'
}

export {
    actions
}